/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Every Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.EveryExpression#getDurationExpression <em>Duration Expression</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.EveryExpression#getNextdurationExpression <em>Nextduration Expression</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getEveryExpression()
 * @model
 * @generated
 */
public interface EveryExpression extends EventCondition
{
  /**
   * Returns the value of the '<em><b>Duration Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration Expression</em>' containment reference.
   * @see #setDurationExpression(Expression)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getEveryExpression_DurationExpression()
   * @model containment="true"
   * @generated
   */
  Expression getDurationExpression();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.EveryExpression#getDurationExpression <em>Duration Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration Expression</em>' containment reference.
   * @see #getDurationExpression()
   * @generated
   */
  void setDurationExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Nextduration Expression</b></em>' containment reference list.
   * The list contents are of type {@link de.bmwgroup.openscenario.asam.openScenario.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nextduration Expression</em>' containment reference list.
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getEveryExpression_NextdurationExpression()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getNextdurationExpression();

} // EveryExpression
