/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EventCondition
{
} // Expression
