/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Access Tail</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.FieldAccessTail#getFieldAccess <em>Field Access</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getFieldAccessTail()
 * @model
 * @generated
 */
public interface FieldAccessTail extends PostfixExpTail
{
  /**
   * Returns the value of the '<em><b>Field Access</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Access</em>' attribute.
   * @see #setFieldAccess(String)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getFieldAccessTail_FieldAccess()
   * @model
   * @generated
   */
  String getFieldAccess();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.FieldAccessTail#getFieldAccess <em>Field Access</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Access</em>' attribute.
   * @see #getFieldAccess()
   * @generated
   */
  void setFieldAccess(String value);

} // FieldAccessTail
