/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Member Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getMemberDeclaration()
 * @model
 * @generated
 */
public interface MemberDeclaration extends ExtensionMemberDeclaration
{
} // MemberDeclaration
