/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Named Argument</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.NamedArgument#getArgumentName <em>Argument Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.NamedArgument#getExpression <em>Expression</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.NamedArgument#getArgumentList <em>Argument List</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getNamedArgument()
 * @model
 * @generated
 */
public interface NamedArgument extends EObject
{
  /**
   * Returns the value of the '<em><b>Argument Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument Name</em>' attribute.
   * @see #setArgumentName(String)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getNamedArgument_ArgumentName()
   * @model
   * @generated
   */
  String getArgumentName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.NamedArgument#getArgumentName <em>Argument Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument Name</em>' attribute.
   * @see #getArgumentName()
   * @generated
   */
  void setArgumentName(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getNamedArgument_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.NamedArgument#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Argument List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument List</em>' containment reference.
   * @see #setArgumentList(ArgumentList)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getNamedArgument_ArgumentList()
   * @model containment="true"
   * @generated
   */
  ArgumentList getArgumentList();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.NamedArgument#getArgumentList <em>Argument List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument List</em>' containment reference.
   * @see #getArgumentList()
   * @generated
   */
  void setArgumentList(ArgumentList value);

} // NamedArgument
