/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Osc File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.OscFile#getPreludeStatements <em>Prelude Statements</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.OscFile#getOscDeclarations <em>Osc Declarations</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getOscFile()
 * @model
 * @generated
 */
public interface OscFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Prelude Statements</b></em>' containment reference list.
   * The list contents are of type {@link de.bmwgroup.openscenario.asam.openScenario.PreludeStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prelude Statements</em>' containment reference list.
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getOscFile_PreludeStatements()
   * @model containment="true"
   * @generated
   */
  EList<PreludeStatement> getPreludeStatements();

  /**
   * Returns the value of the '<em><b>Osc Declarations</b></em>' containment reference list.
   * The list contents are of type {@link de.bmwgroup.openscenario.asam.openScenario.OscDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Osc Declarations</em>' containment reference list.
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getOscFile_OscDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<OscDeclaration> getOscDeclarations();

} // OscFile
