/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Postfix Exp Tail</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getPostfixExpTail()
 * @model
 * @generated
 */
public interface PostfixExpTail extends EObject
{
} // PostfixExpTail
