/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range Constructor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.RangeConstructor#getStart <em>Start</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.RangeConstructor#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getRangeConstructor()
 * @model
 * @generated
 */
public interface RangeConstructor extends PrimaryExp
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(ValueExp)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getRangeConstructor_Start()
   * @model containment="true"
   * @generated
   */
  ValueExp getStart();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.RangeConstructor#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(ValueExp value);

  /**
   * Returns the value of the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' containment reference.
   * @see #setEnd(ValueExp)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getRangeConstructor_End()
   * @model containment="true"
   * @generated
   */
  ValueExp getEnd();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.RangeConstructor#getEnd <em>End</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' containment reference.
   * @see #getEnd()
   * @generated
   */
  void setEnd(ValueExp value);

} // RangeConstructor
