/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sample Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.SampleExpression#getExpression <em>Expression</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.SampleExpression#getEventSpecification <em>Event Specification</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.SampleExpression#getDefaultValue <em>Default Value</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSampleExpression()
 * @model
 * @generated
 */
public interface SampleExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSampleExpression_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.SampleExpression#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Event Specification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Specification</em>' containment reference.
   * @see #setEventSpecification(EventSpecification)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSampleExpression_EventSpecification()
   * @model containment="true"
   * @generated
   */
  EventSpecification getEventSpecification();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.SampleExpression#getEventSpecification <em>Event Specification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Specification</em>' containment reference.
   * @see #getEventSpecification()
   * @generated
   */
  void setEventSpecification(EventSpecification value);

  /**
   * Returns the value of the '<em><b>Default Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Value</em>' containment reference.
   * @see #setDefaultValue(Expression)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSampleExpression_DefaultValue()
   * @model containment="true"
   * @generated
   */
  Expression getDefaultValue();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.SampleExpression#getDefaultValue <em>Default Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Value</em>' containment reference.
   * @see #getDefaultValue()
   * @generated
   */
  void setDefaultValue(Expression value);

} // SampleExpression
