/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SI Base Exponent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.SIBaseExponent#getUnit <em>Unit</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.SIBaseExponent#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSIBaseExponent()
 * @model
 * @generated
 */
public interface SIBaseExponent extends EObject
{
  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSIBaseExponent_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.SIBaseExponent#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(String)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSIBaseExponent_Number()
   * @model
   * @generated
   */
  String getNumber();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.SIBaseExponent#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(String value);

} // SIBaseExponent
