/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SI Base Unit Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.SIBaseUnitSpecifier#getSIBaseExponentList <em>SI Base Exponent List</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSIBaseUnitSpecifier()
 * @model
 * @generated
 */
public interface SIBaseUnitSpecifier extends EObject
{
  /**
   * Returns the value of the '<em><b>SI Base Exponent List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SI Base Exponent List</em>' containment reference.
   * @see #setSIBaseExponentList(SIBaseExponentList)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getSIBaseUnitSpecifier_SIBaseExponentList()
   * @model containment="true"
   * @generated
   */
  SIBaseExponentList getSIBaseExponentList();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.SIBaseUnitSpecifier#getSIBaseExponentList <em>SI Base Exponent List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SI Base Exponent List</em>' containment reference.
   * @see #getSIBaseExponentList()
   * @generated
   */
  void setSIBaseExponentList(SIBaseExponentList value);

} // SIBaseUnitSpecifier
