/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Extension</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getTypeExtension()
 * @model
 * @generated
 */
public interface TypeExtension extends OscDeclaration
{
} // TypeExtension
