/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.UnitDeclaration#getUnitName <em>Unit Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.UnitDeclaration#getPhysicalTypeName <em>Physical Type Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.UnitDeclaration#getUnitSpecifier <em>Unit Specifier</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getUnitDeclaration()
 * @model
 * @generated
 */
public interface UnitDeclaration extends OscDeclaration
{
  /**
   * Returns the value of the '<em><b>Unit Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit Name</em>' attribute.
   * @see #setUnitName(String)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getUnitDeclaration_UnitName()
   * @model
   * @generated
   */
  String getUnitName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.UnitDeclaration#getUnitName <em>Unit Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit Name</em>' attribute.
   * @see #getUnitName()
   * @generated
   */
  void setUnitName(String value);

  /**
   * Returns the value of the '<em><b>Physical Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Physical Type Name</em>' attribute.
   * @see #setPhysicalTypeName(String)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getUnitDeclaration_PhysicalTypeName()
   * @model
   * @generated
   */
  String getPhysicalTypeName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.UnitDeclaration#getPhysicalTypeName <em>Physical Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Physical Type Name</em>' attribute.
   * @see #getPhysicalTypeName()
   * @generated
   */
  void setPhysicalTypeName(String value);

  /**
   * Returns the value of the '<em><b>Unit Specifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit Specifier</em>' containment reference.
   * @see #setUnitSpecifier(SIUnitSpecifier)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getUnitDeclaration_UnitSpecifier()
   * @model containment="true"
   * @generated
   */
  SIUnitSpecifier getUnitSpecifier();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.UnitDeclaration#getUnitSpecifier <em>Unit Specifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit Specifier</em>' containment reference.
   * @see #getUnitSpecifier()
   * @generated
   */
  void setUnitSpecifier(SIUnitSpecifier value);

} // UnitDeclaration
