/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.VariableDeclaration#getSampleExpression <em>Sample Expression</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getVariableDeclaration()
 * @model
 * @generated
 */
public interface VariableDeclaration extends FieldDeclaration
{
  /**
   * Returns the value of the '<em><b>Sample Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sample Expression</em>' containment reference.
   * @see #setSampleExpression(SampleExpression)
   * @see de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage#getVariableDeclaration_SampleExpression()
   * @model containment="true"
   * @generated
   */
  SampleExpression getSampleExpression();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.asam.openScenario.VariableDeclaration#getSampleExpression <em>Sample Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sample Expression</em>' containment reference.
   * @see #getSampleExpression()
   * @generated
   */
  void setSampleExpression(SampleExpression value);

} // VariableDeclaration
