/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getBaseActionName <em>Base Action Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getFieldName <em>Field Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getEnumReference <em>Enum Reference</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getActionMemberDecl <em>Action Member Decl</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getActionDeclaration()
 * @model
 * @generated
 */
public interface ActionDeclaration extends OscDeclaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getActionDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Base Action Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Action Name</em>' attribute.
   * @see #setBaseActionName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getActionDeclaration_BaseActionName()
   * @model
   * @generated
   */
  String getBaseActionName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getBaseActionName <em>Base Action Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Action Name</em>' attribute.
   * @see #getBaseActionName()
   * @generated
   */
  void setBaseActionName(String value);

  /**
   * Returns the value of the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Name</em>' attribute.
   * @see #setFieldName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getActionDeclaration_FieldName()
   * @model
   * @generated
   */
  String getFieldName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getFieldName <em>Field Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Name</em>' attribute.
   * @see #getFieldName()
   * @generated
   */
  void setFieldName(String value);

  /**
   * Returns the value of the '<em><b>Enum Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Reference</em>' containment reference.
   * @see #setEnumReference(EnumValueReference)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getActionDeclaration_EnumReference()
   * @model containment="true"
   * @generated
   */
  EnumValueReference getEnumReference();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ActionDeclaration#getEnumReference <em>Enum Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enum Reference</em>' containment reference.
   * @see #getEnumReference()
   * @generated
   */
  void setEnumReference(EnumValueReference value);

  /**
   * Returns the value of the '<em><b>Action Member Decl</b></em>' containment reference list.
   * The list contents are of type {@link de.bmwgroup.openscenario.openScenario.MemberDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Member Decl</em>' containment reference list.
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getActionDeclaration_ActionMemberDecl()
   * @model containment="true"
   * @generated
   */
  EList<MemberDeclaration> getActionMemberDecl();

} // ActionDeclaration
