/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getConstraintDeclaration()
 * @model
 * @generated
 */
public interface ConstraintDeclaration extends MemberDeclaration, BehaviorWithMember
{
} // ConstraintDeclaration
