/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Do Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.DoDirective#getDoMembers <em>Do Members</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getDoDirective()
 * @model
 * @generated
 */
public interface DoDirective extends BehaviorSpecification
{
  /**
   * Returns the value of the '<em><b>Do Members</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Do Members</em>' containment reference.
   * @see #setDoMembers(DoDirectiveMember)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getDoDirective_DoMembers()
   * @model containment="true"
   * @generated
   */
  DoDirectiveMember getDoMembers();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.DoDirective#getDoMembers <em>Do Members</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Do Members</em>' containment reference.
   * @see #getDoMembers()
   * @generated
   */
  void setDoMembers(DoDirectiveMember value);

} // DoDirective
