/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Emit Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.EmitDirective#getEventName <em>Event Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.EmitDirective#getArgumentList <em>Argument List</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getEmitDirective()
 * @model
 * @generated
 */
public interface EmitDirective extends OnDirectiveMember
{
  /**
   * Returns the value of the '<em><b>Event Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Name</em>' attribute.
   * @see #setEventName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getEmitDirective_EventName()
   * @model
   * @generated
   */
  String getEventName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.EmitDirective#getEventName <em>Event Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Name</em>' attribute.
   * @see #getEventName()
   * @generated
   */
  void setEventName(String value);

  /**
   * Returns the value of the '<em><b>Argument List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument List</em>' containment reference.
   * @see #setArgumentList(ArgumentList)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getEmitDirective_ArgumentList()
   * @model containment="true"
   * @generated
   */
  ArgumentList getArgumentList();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.EmitDirective#getArgumentList <em>Argument List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument List</em>' containment reference.
   * @see #getArgumentList()
   * @generated
   */
  void setArgumentList(ArgumentList value);

} // EmitDirective
