/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Path</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.EventPath#getExpression <em>Expression</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.EventPath#getEventName <em>Event Name</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getEventPath()
 * @model
 * @generated
 */
public interface EventPath extends EObject
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getEventPath_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.EventPath#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Event Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Name</em>' attribute.
   * @see #setEventName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getEventPath_EventName()
   * @model
   * @generated
   */
  String getEventName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.EventPath#getEventName <em>Event Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Name</em>' attribute.
   * @see #getEventName()
   * @generated
   */
  void setEventName(String value);

} // EventPath
