/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Access Tail</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.FieldAccessTail#getFieldName <em>Field Name</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getFieldAccessTail()
 * @model
 * @generated
 */
public interface FieldAccessTail extends PostfixExpTail
{
  /**
   * Returns the value of the '<em><b>Field Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Name</em>' attribute list.
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getFieldAccessTail_FieldName()
   * @model unique="false"
   * @generated
   */
  EList<String> getFieldName();

} // FieldAccessTail
