/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>On Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.OnDirective#getEventSpecification <em>Event Specification</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.OnDirective#getOnMember <em>On Member</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getOnDirective()
 * @model
 * @generated
 */
public interface OnDirective extends BehaviorSpecification
{
  /**
   * Returns the value of the '<em><b>Event Specification</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Specification</em>' attribute.
   * @see #setEventSpecification(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getOnDirective_EventSpecification()
   * @model
   * @generated
   */
  String getEventSpecification();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.OnDirective#getEventSpecification <em>Event Specification</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Specification</em>' attribute.
   * @see #getEventSpecification()
   * @generated
   */
  void setEventSpecification(String value);

  /**
   * Returns the value of the '<em><b>On Member</b></em>' containment reference list.
   * The list contents are of type {@link de.bmwgroup.openscenario.openScenario.OnDirectiveMember}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Member</em>' containment reference list.
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getOnDirective_OnMember()
   * @model containment="true"
   * @generated
   */
  EList<OnDirectiveMember> getOnMember();

} // OnDirective
