/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ParameterDeclaration#getWithDeclaration <em>With Declaration</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getParameterDeclaration()
 * @model
 * @generated
 */
public interface ParameterDeclaration extends FieldDeclaration
{
  /**
   * Returns the value of the '<em><b>With Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>With Declaration</em>' containment reference.
   * @see #setWithDeclaration(ParameterWithDeclaration)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getParameterDeclaration_WithDeclaration()
   * @model containment="true"
   * @generated
   */
  ParameterWithDeclaration getWithDeclaration();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ParameterDeclaration#getWithDeclaration <em>With Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>With Declaration</em>' containment reference.
   * @see #getWithDeclaration()
   * @generated
   */
  void setWithDeclaration(ParameterWithDeclaration value);

} // ParameterDeclaration
