/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prelude Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getPreludeStatement()
 * @model
 * @generated
 */
public interface PreludeStatement extends EObject
{
} // PreludeStatement
