/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getBaseScenarioName <em>Base Scenario Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getFieldName <em>Field Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getEnumReference <em>Enum Reference</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getScenarioMemberDecl <em>Scenario Member Decl</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getBehaviorSpecification <em>Behavior Specification</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getScenarioDeclaration()
 * @model
 * @generated
 */
public interface ScenarioDeclaration extends OscDeclaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getScenarioDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Base Scenario Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Scenario Name</em>' attribute.
   * @see #setBaseScenarioName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getScenarioDeclaration_BaseScenarioName()
   * @model
   * @generated
   */
  String getBaseScenarioName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getBaseScenarioName <em>Base Scenario Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Scenario Name</em>' attribute.
   * @see #getBaseScenarioName()
   * @generated
   */
  void setBaseScenarioName(String value);

  /**
   * Returns the value of the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Name</em>' attribute.
   * @see #setFieldName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getScenarioDeclaration_FieldName()
   * @model
   * @generated
   */
  String getFieldName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getFieldName <em>Field Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Name</em>' attribute.
   * @see #getFieldName()
   * @generated
   */
  void setFieldName(String value);

  /**
   * Returns the value of the '<em><b>Enum Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Reference</em>' containment reference.
   * @see #setEnumReference(EnumValueReference)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getScenarioDeclaration_EnumReference()
   * @model containment="true"
   * @generated
   */
  EnumValueReference getEnumReference();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.ScenarioDeclaration#getEnumReference <em>Enum Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enum Reference</em>' containment reference.
   * @see #getEnumReference()
   * @generated
   */
  void setEnumReference(EnumValueReference value);

  /**
   * Returns the value of the '<em><b>Scenario Member Decl</b></em>' containment reference list.
   * The list contents are of type {@link de.bmwgroup.openscenario.openScenario.MemberDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenario Member Decl</em>' containment reference list.
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getScenarioDeclaration_ScenarioMemberDecl()
   * @model containment="true"
   * @generated
   */
  EList<MemberDeclaration> getScenarioMemberDecl();

  /**
   * Returns the value of the '<em><b>Behavior Specification</b></em>' containment reference list.
   * The list contents are of type {@link de.bmwgroup.openscenario.openScenario.BehaviorSpecification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behavior Specification</em>' containment reference list.
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getScenarioDeclaration_BehaviorSpecification()
   * @model containment="true"
   * @generated
   */
  EList<BehaviorSpecification> getBehaviorSpecification();

} // ScenarioDeclaration
