/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struct Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getBaseStructName <em>Base Struct Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getFieldName <em>Field Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getEnumReference <em>Enum Reference</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getStructMemberDecl <em>Struct Member Decl</em>}</li>
 * </ul>
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getStructDeclaration()
 * @model
 * @generated
 */
public interface StructDeclaration extends OscDeclaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getStructDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Base Struct Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Struct Name</em>' attribute.
   * @see #setBaseStructName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getStructDeclaration_BaseStructName()
   * @model
   * @generated
   */
  String getBaseStructName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getBaseStructName <em>Base Struct Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Struct Name</em>' attribute.
   * @see #getBaseStructName()
   * @generated
   */
  void setBaseStructName(String value);

  /**
   * Returns the value of the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Name</em>' attribute.
   * @see #setFieldName(String)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getStructDeclaration_FieldName()
   * @model
   * @generated
   */
  String getFieldName();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getFieldName <em>Field Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Name</em>' attribute.
   * @see #getFieldName()
   * @generated
   */
  void setFieldName(String value);

  /**
   * Returns the value of the '<em><b>Enum Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Reference</em>' containment reference.
   * @see #setEnumReference(EnumValueReference)
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getStructDeclaration_EnumReference()
   * @model containment="true"
   * @generated
   */
  EnumValueReference getEnumReference();

  /**
   * Sets the value of the '{@link de.bmwgroup.openscenario.openScenario.StructDeclaration#getEnumReference <em>Enum Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enum Reference</em>' containment reference.
   * @see #getEnumReference()
   * @generated
   */
  void setEnumReference(EnumValueReference value);

  /**
   * Returns the value of the '<em><b>Struct Member Decl</b></em>' containment reference list.
   * The list contents are of type {@link de.bmwgroup.openscenario.openScenario.MemberDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Struct Member Decl</em>' containment reference list.
   * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getStructDeclaration_StructMemberDecl()
   * @model containment="true"
   * @generated
   */
  EList<MemberDeclaration> getStructMemberDecl();

} // StructDeclaration
