/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.bmwgroup.openscenario.openScenario.OpenScenarioPackage#getValueExp()
 * @model
 * @generated
 */
public interface ValueExp extends PrimaryExp
{
} // ValueExp
