/*
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOpenScenarioScopeProvider extends DelegatingScopeProvider {
}
