/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario.impl;

import de.bmwgroup.openscenario.asam.openScenario.ElapsedExpression;
import de.bmwgroup.openscenario.asam.openScenario.Expression;
import de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Elapsed Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.ElapsedExpressionImpl#getDurationExpression <em>Duration Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ElapsedExpressionImpl extends EventConditionImpl implements ElapsedExpression
{
  /**
   * The cached value of the '{@link #getDurationExpression() <em>Duration Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDurationExpression()
   * @generated
   * @ordered
   */
  protected Expression durationExpression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElapsedExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenScenarioPackage.Literals.ELAPSED_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getDurationExpression()
  {
    return durationExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDurationExpression(Expression newDurationExpression, NotificationChain msgs)
  {
    Expression oldDurationExpression = durationExpression;
    durationExpression = newDurationExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION, oldDurationExpression, newDurationExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDurationExpression(Expression newDurationExpression)
  {
    if (newDurationExpression != durationExpression)
    {
      NotificationChain msgs = null;
      if (durationExpression != null)
        msgs = ((InternalEObject)durationExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION, null, msgs);
      if (newDurationExpression != null)
        msgs = ((InternalEObject)newDurationExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION, null, msgs);
      msgs = basicSetDurationExpression(newDurationExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION, newDurationExpression, newDurationExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION:
        return basicSetDurationExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION:
        return getDurationExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION:
        setDurationExpression((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION:
        setDurationExpression((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ELAPSED_EXPRESSION__DURATION_EXPRESSION:
        return durationExpression != null;
    }
    return super.eIsSet(featureID);
  }

} //ElapsedExpressionImpl
