/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario.impl;

import de.bmwgroup.openscenario.asam.openScenario.EnumValueReference;
import de.bmwgroup.openscenario.asam.openScenario.MemberDeclaration;
import de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage;
import de.bmwgroup.openscenario.asam.openScenario.StructDeclaration;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Struct Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.StructDeclarationImpl#getName <em>Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.StructDeclarationImpl#getBaseStructName <em>Base Struct Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.StructDeclarationImpl#getFieldName <em>Field Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.StructDeclarationImpl#getEnumReference <em>Enum Reference</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.StructDeclarationImpl#getStructMemberDecl <em>Struct Member Decl</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StructDeclarationImpl extends OscDeclarationImpl implements StructDeclaration
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getBaseStructName() <em>Base Struct Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBaseStructName()
   * @generated
   * @ordered
   */
  protected static final String BASE_STRUCT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBaseStructName() <em>Base Struct Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBaseStructName()
   * @generated
   * @ordered
   */
  protected String baseStructName = BASE_STRUCT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getFieldName() <em>Field Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldName()
   * @generated
   * @ordered
   */
  protected static final String FIELD_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFieldName() <em>Field Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldName()
   * @generated
   * @ordered
   */
  protected String fieldName = FIELD_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEnumReference() <em>Enum Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumReference()
   * @generated
   * @ordered
   */
  protected EnumValueReference enumReference;

  /**
   * The cached value of the '{@link #getStructMemberDecl() <em>Struct Member Decl</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructMemberDecl()
   * @generated
   * @ordered
   */
  protected EList<MemberDeclaration> structMemberDecl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StructDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenScenarioPackage.Literals.STRUCT_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.STRUCT_DECLARATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBaseStructName()
  {
    return baseStructName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBaseStructName(String newBaseStructName)
  {
    String oldBaseStructName = baseStructName;
    baseStructName = newBaseStructName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.STRUCT_DECLARATION__BASE_STRUCT_NAME, oldBaseStructName, baseStructName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFieldName()
  {
    return fieldName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFieldName(String newFieldName)
  {
    String oldFieldName = fieldName;
    fieldName = newFieldName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.STRUCT_DECLARATION__FIELD_NAME, oldFieldName, fieldName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EnumValueReference getEnumReference()
  {
    return enumReference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnumReference(EnumValueReference newEnumReference, NotificationChain msgs)
  {
    EnumValueReference oldEnumReference = enumReference;
    enumReference = newEnumReference;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE, oldEnumReference, newEnumReference);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnumReference(EnumValueReference newEnumReference)
  {
    if (newEnumReference != enumReference)
    {
      NotificationChain msgs = null;
      if (enumReference != null)
        msgs = ((InternalEObject)enumReference).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE, null, msgs);
      if (newEnumReference != null)
        msgs = ((InternalEObject)newEnumReference).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE, null, msgs);
      msgs = basicSetEnumReference(newEnumReference, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE, newEnumReference, newEnumReference));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MemberDeclaration> getStructMemberDecl()
  {
    if (structMemberDecl == null)
    {
      structMemberDecl = new EObjectContainmentEList<MemberDeclaration>(MemberDeclaration.class, this, OpenScenarioPackage.STRUCT_DECLARATION__STRUCT_MEMBER_DECL);
    }
    return structMemberDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE:
        return basicSetEnumReference(null, msgs);
      case OpenScenarioPackage.STRUCT_DECLARATION__STRUCT_MEMBER_DECL:
        return ((InternalEList<?>)getStructMemberDecl()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.STRUCT_DECLARATION__NAME:
        return getName();
      case OpenScenarioPackage.STRUCT_DECLARATION__BASE_STRUCT_NAME:
        return getBaseStructName();
      case OpenScenarioPackage.STRUCT_DECLARATION__FIELD_NAME:
        return getFieldName();
      case OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE:
        return getEnumReference();
      case OpenScenarioPackage.STRUCT_DECLARATION__STRUCT_MEMBER_DECL:
        return getStructMemberDecl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.STRUCT_DECLARATION__NAME:
        setName((String)newValue);
        return;
      case OpenScenarioPackage.STRUCT_DECLARATION__BASE_STRUCT_NAME:
        setBaseStructName((String)newValue);
        return;
      case OpenScenarioPackage.STRUCT_DECLARATION__FIELD_NAME:
        setFieldName((String)newValue);
        return;
      case OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE:
        setEnumReference((EnumValueReference)newValue);
        return;
      case OpenScenarioPackage.STRUCT_DECLARATION__STRUCT_MEMBER_DECL:
        getStructMemberDecl().clear();
        getStructMemberDecl().addAll((Collection<? extends MemberDeclaration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.STRUCT_DECLARATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case OpenScenarioPackage.STRUCT_DECLARATION__BASE_STRUCT_NAME:
        setBaseStructName(BASE_STRUCT_NAME_EDEFAULT);
        return;
      case OpenScenarioPackage.STRUCT_DECLARATION__FIELD_NAME:
        setFieldName(FIELD_NAME_EDEFAULT);
        return;
      case OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE:
        setEnumReference((EnumValueReference)null);
        return;
      case OpenScenarioPackage.STRUCT_DECLARATION__STRUCT_MEMBER_DECL:
        getStructMemberDecl().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.STRUCT_DECLARATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case OpenScenarioPackage.STRUCT_DECLARATION__BASE_STRUCT_NAME:
        return BASE_STRUCT_NAME_EDEFAULT == null ? baseStructName != null : !BASE_STRUCT_NAME_EDEFAULT.equals(baseStructName);
      case OpenScenarioPackage.STRUCT_DECLARATION__FIELD_NAME:
        return FIELD_NAME_EDEFAULT == null ? fieldName != null : !FIELD_NAME_EDEFAULT.equals(fieldName);
      case OpenScenarioPackage.STRUCT_DECLARATION__ENUM_REFERENCE:
        return enumReference != null;
      case OpenScenarioPackage.STRUCT_DECLARATION__STRUCT_MEMBER_DECL:
        return structMemberDecl != null && !structMemberDecl.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", baseStructName: ");
    result.append(baseStructName);
    result.append(", fieldName: ");
    result.append(fieldName);
    result.append(')');
    return result.toString();
  }

} //StructDeclarationImpl
