/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.openScenario.impl;

import de.bmwgroup.openscenario.asam.openScenario.OpenScenarioPackage;
import de.bmwgroup.openscenario.asam.openScenario.SIUnitSpecifier;
import de.bmwgroup.openscenario.asam.openScenario.UnitDeclaration;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Unit Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.UnitDeclarationImpl#getUnitName <em>Unit Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.UnitDeclarationImpl#getPhysicalTypeName <em>Physical Type Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.asam.openScenario.impl.UnitDeclarationImpl#getUnitSpecifier <em>Unit Specifier</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UnitDeclarationImpl extends OscDeclarationImpl implements UnitDeclaration
{
  /**
   * The default value of the '{@link #getUnitName() <em>Unit Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnitName()
   * @generated
   * @ordered
   */
  protected static final String UNIT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUnitName() <em>Unit Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnitName()
   * @generated
   * @ordered
   */
  protected String unitName = UNIT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPhysicalTypeName() <em>Physical Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhysicalTypeName()
   * @generated
   * @ordered
   */
  protected static final String PHYSICAL_TYPE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPhysicalTypeName() <em>Physical Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhysicalTypeName()
   * @generated
   * @ordered
   */
  protected String physicalTypeName = PHYSICAL_TYPE_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getUnitSpecifier() <em>Unit Specifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnitSpecifier()
   * @generated
   * @ordered
   */
  protected SIUnitSpecifier unitSpecifier;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UnitDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenScenarioPackage.Literals.UNIT_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUnitName()
  {
    return unitName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnitName(String newUnitName)
  {
    String oldUnitName = unitName;
    unitName = newUnitName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.UNIT_DECLARATION__UNIT_NAME, oldUnitName, unitName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPhysicalTypeName()
  {
    return physicalTypeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPhysicalTypeName(String newPhysicalTypeName)
  {
    String oldPhysicalTypeName = physicalTypeName;
    physicalTypeName = newPhysicalTypeName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.UNIT_DECLARATION__PHYSICAL_TYPE_NAME, oldPhysicalTypeName, physicalTypeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SIUnitSpecifier getUnitSpecifier()
  {
    return unitSpecifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUnitSpecifier(SIUnitSpecifier newUnitSpecifier, NotificationChain msgs)
  {
    SIUnitSpecifier oldUnitSpecifier = unitSpecifier;
    unitSpecifier = newUnitSpecifier;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER, oldUnitSpecifier, newUnitSpecifier);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnitSpecifier(SIUnitSpecifier newUnitSpecifier)
  {
    if (newUnitSpecifier != unitSpecifier)
    {
      NotificationChain msgs = null;
      if (unitSpecifier != null)
        msgs = ((InternalEObject)unitSpecifier).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER, null, msgs);
      if (newUnitSpecifier != null)
        msgs = ((InternalEObject)newUnitSpecifier).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER, null, msgs);
      msgs = basicSetUnitSpecifier(newUnitSpecifier, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER, newUnitSpecifier, newUnitSpecifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER:
        return basicSetUnitSpecifier(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_NAME:
        return getUnitName();
      case OpenScenarioPackage.UNIT_DECLARATION__PHYSICAL_TYPE_NAME:
        return getPhysicalTypeName();
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER:
        return getUnitSpecifier();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_NAME:
        setUnitName((String)newValue);
        return;
      case OpenScenarioPackage.UNIT_DECLARATION__PHYSICAL_TYPE_NAME:
        setPhysicalTypeName((String)newValue);
        return;
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER:
        setUnitSpecifier((SIUnitSpecifier)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_NAME:
        setUnitName(UNIT_NAME_EDEFAULT);
        return;
      case OpenScenarioPackage.UNIT_DECLARATION__PHYSICAL_TYPE_NAME:
        setPhysicalTypeName(PHYSICAL_TYPE_NAME_EDEFAULT);
        return;
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER:
        setUnitSpecifier((SIUnitSpecifier)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_NAME:
        return UNIT_NAME_EDEFAULT == null ? unitName != null : !UNIT_NAME_EDEFAULT.equals(unitName);
      case OpenScenarioPackage.UNIT_DECLARATION__PHYSICAL_TYPE_NAME:
        return PHYSICAL_TYPE_NAME_EDEFAULT == null ? physicalTypeName != null : !PHYSICAL_TYPE_NAME_EDEFAULT.equals(physicalTypeName);
      case OpenScenarioPackage.UNIT_DECLARATION__UNIT_SPECIFIER:
        return unitSpecifier != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (unitName: ");
    result.append(unitName);
    result.append(", physicalTypeName: ");
    result.append(physicalTypeName);
    result.append(')');
    return result.toString();
  }

} //UnitDeclarationImpl
