/*
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OpenScenarioRuntimeModule extends AbstractOpenScenarioRuntimeModule {
}
