/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario.impl;

import de.bmwgroup.openscenario.openScenario.EnumDeclaration;
import de.bmwgroup.openscenario.openScenario.EnumMemberDeclaration;
import de.bmwgroup.openscenario.openScenario.OpenScenarioPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enum Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.impl.EnumDeclarationImpl#getEnumName <em>Enum Name</em>}</li>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.impl.EnumDeclarationImpl#getEnumMemberDecls <em>Enum Member Decls</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnumDeclarationImpl extends OscDeclarationImpl implements EnumDeclaration
{
  /**
   * The default value of the '{@link #getEnumName() <em>Enum Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumName()
   * @generated
   * @ordered
   */
  protected static final String ENUM_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnumName() <em>Enum Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumName()
   * @generated
   * @ordered
   */
  protected String enumName = ENUM_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEnumMemberDecls() <em>Enum Member Decls</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumMemberDecls()
   * @generated
   * @ordered
   */
  protected EList<EnumMemberDeclaration> enumMemberDecls;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnumDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenScenarioPackage.Literals.ENUM_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEnumName()
  {
    return enumName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnumName(String newEnumName)
  {
    String oldEnumName = enumName;
    enumName = newEnumName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.ENUM_DECLARATION__ENUM_NAME, oldEnumName, enumName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EnumMemberDeclaration> getEnumMemberDecls()
  {
    if (enumMemberDecls == null)
    {
      enumMemberDecls = new EObjectContainmentEList<EnumMemberDeclaration>(EnumMemberDeclaration.class, this, OpenScenarioPackage.ENUM_DECLARATION__ENUM_MEMBER_DECLS);
    }
    return enumMemberDecls;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_MEMBER_DECLS:
        return ((InternalEList<?>)getEnumMemberDecls()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_NAME:
        return getEnumName();
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_MEMBER_DECLS:
        return getEnumMemberDecls();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_NAME:
        setEnumName((String)newValue);
        return;
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_MEMBER_DECLS:
        getEnumMemberDecls().clear();
        getEnumMemberDecls().addAll((Collection<? extends EnumMemberDeclaration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_NAME:
        setEnumName(ENUM_NAME_EDEFAULT);
        return;
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_MEMBER_DECLS:
        getEnumMemberDecls().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_NAME:
        return ENUM_NAME_EDEFAULT == null ? enumName != null : !ENUM_NAME_EDEFAULT.equals(enumName);
      case OpenScenarioPackage.ENUM_DECLARATION__ENUM_MEMBER_DECLS:
        return enumMemberDecls != null && !enumMemberDecls.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (enumName: ");
    result.append(enumName);
    result.append(')');
    return result.toString();
  }

} //EnumDeclarationImpl
