/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario.impl;

import de.bmwgroup.openscenario.openScenario.ConstraintDeclaration;
import de.bmwgroup.openscenario.openScenario.OpenScenarioPackage;
import de.bmwgroup.openscenario.openScenario.ParameterWithDeclaration;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parameter With Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.impl.ParameterWithDeclarationImpl#getParameterWithMembers <em>Parameter With Members</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParameterWithDeclarationImpl extends MinimalEObjectImpl.Container implements ParameterWithDeclaration
{
  /**
   * The cached value of the '{@link #getParameterWithMembers() <em>Parameter With Members</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameterWithMembers()
   * @generated
   * @ordered
   */
  protected EList<ConstraintDeclaration> parameterWithMembers;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParameterWithDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenScenarioPackage.Literals.PARAMETER_WITH_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ConstraintDeclaration> getParameterWithMembers()
  {
    if (parameterWithMembers == null)
    {
      parameterWithMembers = new EObjectContainmentEList<ConstraintDeclaration>(ConstraintDeclaration.class, this, OpenScenarioPackage.PARAMETER_WITH_DECLARATION__PARAMETER_WITH_MEMBERS);
    }
    return parameterWithMembers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_WITH_DECLARATION__PARAMETER_WITH_MEMBERS:
        return ((InternalEList<?>)getParameterWithMembers()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_WITH_DECLARATION__PARAMETER_WITH_MEMBERS:
        return getParameterWithMembers();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_WITH_DECLARATION__PARAMETER_WITH_MEMBERS:
        getParameterWithMembers().clear();
        getParameterWithMembers().addAll((Collection<? extends ConstraintDeclaration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_WITH_DECLARATION__PARAMETER_WITH_MEMBERS:
        getParameterWithMembers().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_WITH_DECLARATION__PARAMETER_WITH_MEMBERS:
        return parameterWithMembers != null && !parameterWithMembers.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ParameterWithDeclarationImpl
