/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.openScenario.impl;

import de.bmwgroup.openscenario.openScenario.OpenScenarioPackage;
import de.bmwgroup.openscenario.openScenario.ParameterDeclaration;
import de.bmwgroup.openscenario.openScenario.ParameterWithDeclaration;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parameter Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.bmwgroup.openscenario.openScenario.impl.ParameterDeclarationImpl#getWithDeclaration <em>With Declaration</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParameterDeclarationImpl extends FieldDeclarationImpl implements ParameterDeclaration
{
  /**
   * The cached value of the '{@link #getWithDeclaration() <em>With Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWithDeclaration()
   * @generated
   * @ordered
   */
  protected ParameterWithDeclaration withDeclaration;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParameterDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenScenarioPackage.Literals.PARAMETER_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ParameterWithDeclaration getWithDeclaration()
  {
    return withDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWithDeclaration(ParameterWithDeclaration newWithDeclaration, NotificationChain msgs)
  {
    ParameterWithDeclaration oldWithDeclaration = withDeclaration;
    withDeclaration = newWithDeclaration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION, oldWithDeclaration, newWithDeclaration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWithDeclaration(ParameterWithDeclaration newWithDeclaration)
  {
    if (newWithDeclaration != withDeclaration)
    {
      NotificationChain msgs = null;
      if (withDeclaration != null)
        msgs = ((InternalEObject)withDeclaration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION, null, msgs);
      if (newWithDeclaration != null)
        msgs = ((InternalEObject)newWithDeclaration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION, null, msgs);
      msgs = basicSetWithDeclaration(newWithDeclaration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION, newWithDeclaration, newWithDeclaration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION:
        return basicSetWithDeclaration(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION:
        return getWithDeclaration();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION:
        setWithDeclaration((ParameterWithDeclaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION:
        setWithDeclaration((ParameterWithDeclaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenScenarioPackage.PARAMETER_DECLARATION__WITH_DECLARATION:
        return withDeclaration != null;
    }
    return super.eIsSet(featureID);
  }

} //ParameterDeclarationImpl
