/**
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.tests;

/* @ExtendWith(_InjectionExtension)
@InjectWith(OpenScenarioInjectorProvider.class) */@SuppressWarnings("all")
public class OpenScenarioParsingTest {
  /* @Inject
   */private /* ParseHelper<Model> */Object parseHelper;

  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nThe field OpenScenarioParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
