/*
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.ide;


/**
 * Use this class to register ide components.
 */
public class OpenScenarioIdeModule extends AbstractOpenScenarioIdeModule {
}
