/*
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OpenScenarioAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/bmwgroup/openscenario/asam/parser/antlr/internal/InternalOpenScenarioParser.tokens");
	}
}
