/*
 * generated by Xtext 2.35.0
 */
package de.bmwgroup.openscenario.asam.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.bmwgroup.openscenario.asam.OpenScenarioRuntimeModule;
import de.bmwgroup.openscenario.asam.OpenScenarioStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OpenScenarioIdeSetup extends OpenScenarioStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OpenScenarioRuntimeModule(), new OpenScenarioIdeModule()));
	}
	
}
